### ISSUE TITLE
Port 8080 already in use

### ISSUE THREAD

**Issue by PatrickOnGit** [litinoveweedle/hassio-addons#20] opened 2024-06-12 06:27 UTC
Thank you for creating this addon.

The addon does not start as another addon (unifi Controller im my case) is already using port 8080.

[07:59:01] INFO: netflow2ng --metrics=127.0.0.1:8080 --listen-zmq=tcp://127.0.0.1:5556 --log-level=error --listen=0.0.0.0:2055 --log-level=info
level=info msg="Starting netflow2ng"
level=fatal msg="listen tcp 127.0.0.1:8080: bind: address already in use"
[07:59:01] INFO: Service netflow2ng exited with code 1 (by signal 0)

Is there a way to reconfigure your addon to use a different port? Like providing more configuration options?

Thank you

**Comment by stevehof** [comment] 2024-11-01 09:15
Hi @PatrickOnGit 

Are you using it as a docker container? I found that setting the ntop external port proxies the port, so you can just set the port to a port of your choosing like 3001 instead of 8080 or 80 or 3000 which were all in use for me.

**Comment by PatrickOnGit** [comment] 2024-12-14 17:19
Hi @stevehof 
Thank you for your response. 
I do use it as simple plugin as part of HAOS. So far I didn't try to mess around with any docker configuration settings used behind the scenes and would like to avoid it. It might be much simpler for a home assistant user, if  the port settings would be exposed in the configuration section, maybe as expert settings.
Trying to change docker configuration on HAOS seems a bit risky and requires quite some knowledge.
If possible it would be awesome if the plugin would be extended to allow customizing the ports internally used by the plugin itself, not just the ports accessible and used from  outside the plugin.

Thank you for your support 
Patrick

**Comment by litinoveweedle** [comment] 2024-12-26 15:22
Hello, the issue is fixed in the 0.0.25b2, please test it - it is ow possible to configure any localhost ports as well. If your problem persists please reopen this issue.

**Closed by litinoveweedle** 2024-12-26 15:22 UTC
